apiVersion: "yard.kie.org/v1alpha1"
kind: YaRD
metadata:
  name: helloyard
spec:
  yard:
    # specVersion: alpha
    # kind: YaRD
    # name: 'helloyard'
    # expressionLang: alpha
    inputs:
    - name: 'Age'
      type: number
    - name: 'Previous incidents?'
      type: boolean
    elements:
    - name: 'Base price'
      type: Decision
      logic: 
        type: DecisionTable
        inputs: ['Age', 'Previous incidents?']
        rules:
          - when: ['<21', false]
            then: 806
          - when: ['<21', true]
            then: 1006
          - when: ['>=21', false]
            then: 506
          - when: ['>=21', true]
            then: 606
